services:
  prestashop:
    image: mrktosiek/geekup-prestashop:1.5
    ports:
      - 19305:443
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_193059
      DB_USER: root
      DB_PASSWD: student
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:5242
      PS_SSL_DOMAIN: localhost:5242
      PS_FOLDER_ADMIN: admin2137
      PS_FOLDER_INSTALL: install2137
    networks:
      - admin-mysql_default
      - prestashop_network
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "3G"
        reservations:
          cpus: "1.0"
          memory: "512M"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  memcached:
    image: memcached:latest
    networks:
      - prestashop_network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
        reservations:
          cpus: "0.25"
          memory: "256M"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  prestashop_network:
    driver: overlay
  admin-mysql_default:
    external: true
