version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - ./prestashop/dbdata:/var/lib/mysql

  prestashop:
    container_name: prestashop
    image: mrktosiek/geekup-prestashop:1.0
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./prestashop/psdata:/var/www/html
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      PS_SSL_DOMAIN: localhost:8443
      PS_FOLDER_ADMIN: admin2137
      PS_FOLDER_INSTALL: install2137
    networks:
      - prestashop_network

  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: unless-stopped
    environment:
      PMA_HOST: some-mysql
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - 8081:80
    networks:
      - prestashop_network
      
networks:
  prestashop_network: