<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container15E6ew3\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container15E6ew3/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container15E6ew3.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container15E6ew3\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container15E6ew3\appAppKernelProdContainer([
    'container.build_hash' => '15E6ew3',
    'container.build_id' => '9ee955da',
    'container.build_time' => 1730224037,
], __DIR__.\DIRECTORY_SEPARATOR.'Container15E6ew3');
