<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6nvrejr\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6nvrejr/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6nvrejr.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6nvrejr\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6nvrejr\appProdProjectContainer([
    'container.build_hash' => '6nvrejr',
    'container.build_id' => 'f16b44b7',
    'container.build_time' => 1732293357,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6nvrejr');
