<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxra72m\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxra72m/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFxra72m.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFxra72m\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFxra72m\appProdProjectContainer([
    'container.build_hash' => 'Fxra72m',
    'container.build_id' => '95b96679',
    'container.build_time' => 1730820264,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxra72m');
