<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3h2zx5m\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3h2zx5m/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3h2zx5m.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3h2zx5m\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3h2zx5m\appProdProjectContainer([
    'container.build_hash' => '3h2zx5m',
    'container.build_id' => 'ba4a4c6b',
    'container.build_time' => 1730649070,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3h2zx5m');
