version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - ../prestashop/dbdata:/var/lib/mysql
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:1.7.8.11
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 8443:443  # Add SSL port mapping
    volumes:
      - ../prestashop/psdata:/var/www/html
      - ./certs:/etc/apache2/ssl  # Map certs directory to Apache
      - ./ssl.conf:/etc/apache2/sites-available/default-ssl.conf  # Map ssl configuration file
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      PS_SSL_DOMAIN: localhost:8443   # HTTPS domain (SSL)
      PS_FOLDER_ADMIN: admin2137
      PS_FOLDER_INSTALL: install2137
    networks:
      - prestashop_network
    command: >
      bash -c "
      echo 'ServerName localhost' >> /etc/apache2/apache2.conf &&
      a2enmod ssl &&
      a2ensite default-ssl &&
      apache2-foreground
      "
    
  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: unless-stopped
    environment:
        PMA_HOST: some-mysql
        PMA_USER: root
        PMA_PASSWORD: admin
        PMA_PORT: 3306
    ports:
        - 8081:80
    networks:
        - prestashop_network
networks:
    prestashop_network:
volumes:
  dbdata:
  psdata:
