name: Geekup-Prestashop Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and tag image
        env:
          IMAGE_NAME: geekup-prestashop
          DOCKERFILE_PATH: ./configuration/Dockerfile
        run: |
          docker build -t $IMAGE_NAME:latest -f $DOCKERFILE_PATH .
      
      - name: Save Docker image as a file
        env:
          IMAGE_NAME: geekup-prestashop
        run: |
          docker save $IMAGE_NAME:latest -o image.tar
      
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar

  push:
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
      
      - name: Load Docker image
        run: |
          docker load -i image.tar
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push image to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: geekup-prestashop
        run: |
          docker tag $IMAGE_NAME:latest $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
