name: Geekup-Prestashop Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build_adn_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and tag image
        env:
          IMAGE_NAME: geekup-prestashop
          DOCKERFILE_PATH: ./configuration/Dockerfile
        run: |
          docker build -t $IMAGE_NAME:latest -f $DOCKERFILE_PATH .
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push image to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: geekup-prestashop
        run: |
          docker tag $IMAGE_NAME:latest $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
