name: Geekup-Prestashop Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, tag and push image to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERFILE_PATH: ./configuration/Dockerfile
          IMAGE_NAME: geekup-prestashop
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:1.0 -f $DOCKERFILE_PATH .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:1.0
